### ISSUE TITLE
Integrate SonarCloud for code quality checks.

### ISSUE THREAD

**Issue by IB-12** [G12-Wanderwave/Wanderwave#25]
**Story:** As a software development team, we want to integrate SonarCloud with our GitHub repository. This will allow us to automatically analyze our code for quality and security issues whenever changes are pushed to the main branch.

**Acceptance Criteria:** 

- SonarCloud is set up and configured for our GitHub repository.
- A GitHub Actions workflow is in place to trigger SonarCloud analysis on push events to the main branch.
- The results of the SonarCloud analysis are visible and accessible to the team.

**Tasks**

- [X] Register the project with SonarCloud.
- [x] Update the `build.gradle.kts` file to include the SonarQube plugin and its configuration.
- [x] Create a GitHub Actions workflow file that triggers SonarCloud analysis on push events to the main branch.

**Comment by tsogtb** [comment]
I have added the actions secret **SONAR_TOKEN** to the repository. This secret will be used by SonarCloud to authenticate and analyze our code. Once the project is setup we can add a workflow by:

- Adding the following to our project level build.gradle.kts

```
plugins {
  id("org.sonarqube") version "4.4.1.3373"
}

sonar {
  properties {
    property("sonar.projectKey", "G12-Wanderwave_Wanderwave")
    property("sonar.organization", "g12-wanderwave")
    property("sonar.host.url", "https://sonarcloud.io")
  }
}
```
- Creating a workflow `.github/workflows/sonarcloud-analysis.yml` or alternatively appending our main workflow file to include, @joriba 
```
name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info
```
