### ISSUE TITLE
[DRAFT] Implement Main Screen

### ISSUE THREAD

**Issue by mbouaissi** [G12-Wanderwave/Wanderwave#3]
**User Story:** As a WanderWave user, I want to be able to see a map when I open the application, so that I can see where are the beacons. This screen should also have the functionality to change the way I want to interact with these beacons. 

**Acceptance criteria:** 

- Once I am logged in, I should see this screen
- The screen should have a map centered on my location
- I should see myself on the map
- I should see beacon on the map
- I have the possibility to locate the nearest beacon on the map
- I can be able to change the way I want to interact with these beacons
- I can be able to move the map, to see where other beacons are
- When I two tap the map, I should be able to re-center the map to my location

**Tasks:**

- [ ] Set up a map 
- [ ] Set up beacons location
- [ ] Handle the interaction with the map, like moving the map, center to my location
- [ ] Implement the drop of the song when one pass near it
- [ ] Implement the recovery of a song when one pass near it
- [ ] Implement the way to find the nearest beacon
