### ISSUE TITLE
[DRAFT] Implement Stat Screen

### ISSUE THREAD

**Issue by mbouaissi** [G12-Wanderwave/Wanderwave#4]
**User story:** 
As a user of WanderWave, I want to be able to have a screen where I can see my profile, so that when I interact with the others, they can see who am I. I should also be able to choose which songs I want to drop
**Acceptance criteria:**
- When I am on this screen, I can see something like a visit card, with all my stats, and my profile information (profile picture, name, stats, ...)
- I should be able to set myself as anonymous
- I should be able to select which songs I want to drop

**Optional criteria**
- Enable a user to share his profile

**Tasks:**

- [ ] Implement the profile
- [ ] Implement the fact that a user can select which songs he wants to drop
- [ ] Implement the anonymization of a user
- [ ] Enable the fact that a user can modify his profile
