### ISSUE TITLE
[DRAFT] Implement Songs Screen

### ISSUE THREAD

**Issue by mbouaissi** [G12-Wanderwave/Wanderwave#5]
**User story:**
As a WanderWave user, I want to be able to have a song screen, so that I can see which songs I have recovered while walking, and choose which one I like. 
**Acceptance criteria:**
- I should be able to see all the songs that I have found
- I should be able to like or dislike a song
- I should be able to add a song to my Spotify playlist

**Tasks:**
- [ ] Implement a list of songs that a user has found
- [ ] Implement the fact that when a user like/dislike a song, the ike/dislike is transferred to the profile of the one who has dropped the song
- [ ] Implement adding a song to the Spotify playlist
