### ISSUE TITLE
Organise the first commit

### ISSUE THREAD

**Issue by KlaKalma** [G12-Wanderwave/Wanderwave#6]
To start with the project, we need to make the actual app code project.

**Acceptance criteria:**
The project can build in android studio on every group member's computer

**Tasks:**

- [ ] Make the project
- [ ] Check the gitignore and adapt if needed
- [ ] Make a short example first screen
- [ ] Organise the structure of the MVVM app model
