### ISSUE TITLE
Organise the team

### ISSUE THREAD

**Issue by KlaKalma** [G12-Wanderwave/Wanderwave#7]
To start with the project, we need to organise the group and the group members tasks

**Acceptance criteria:**
Everyone in the group is aware if its tasks for the sprints 

**Tasks:**

- [x] Brainstorm the team to determine the different capabilities
- [x] Determine who does what

- [x] Make the different branches on the GitHub
