### ISSUE TITLE
[DRAFT] Implement offline mode

### ISSUE THREAD

**Issue by mbouaissi** [G12-Wanderwave/Wanderwave#8]
**User story:**
As a user of WanderWave, I want to be able to still use the app when I am not connected to wifi, so that I can keep sharing my songs and seeing my stats.
**Acceptance criteria:**

- When I look at the app, I should be able to see the beacon near me
- When I go near a beacon, I should be able to drop a song
- I should be able to see my stats
- If my song are saved on spotify, I should be able to change which songs I want to drop
- I should be able to modify my profile
- I should be able to see the songs that I have collected before going offline

**Tasks:**
- [ ] Set up a way to cache the beacon in the app
- [ ] Implement a way to drop song to the cached beacon
- [ ] Enable the fact to be able to modify the profile and my songs, and send the updates once online
- [ ] Cache the stats and the collected songs
